# QCArchive Demo
## MolSSI Software Summer School -Day 2

### This is a database that uses qc portal

In [18]:
import qcportal as ptl
import numpy as np

client = ptl.FractalClient()

In [2]:
client

FractalClient(server_name='The MolSSI QCArchive Server', address='https://api.qcarchive.molssi.org:443/', username='None')

In [3]:
# The way it returns are the list of molecules. 
butane = client.query_molecules(id=['61139', '70659'])

In [6]:
butane

[<Molecule(name='C4H10' formula='C4H10' hash='3bbc6db')>,
 <Molecule(name='C4H10' formula='C4H10' hash='bb665a3')>]

In [7]:
butane[0].show()

You appear to be running in JupyterLab (or JavaScript failed to load for some other reason). You need to install the 3dmol extension: 
 jupyter labextension install jupyterlab_3dmol

In [17]:
butane[1]

You appear to be running in JupyterLab (or JavaScript failed to load for some other reason). You need to install the 3dmol extension: 
 jupyter labextension install jupyterlab_3dmol

<Molecule(name='C4H10' formula='C4H10' hash='bb665a3')>

In [10]:
butane[0].scramble()

(<Molecule(name='C4H10' formula='C4H10' hash='31576b8')>,
 {'rmsd': 2.9814323718372964, 'mill': <----------------------------------------
               AlignmentMill              
  ----------------------------------------
  Mirror:   False
  Atom Map: [12 13  1  9 11  8  5  0  2  7  6  4  3 10]
  Shift:    [ 0.1362740926126129 -0.7083064058643216  2.2780175845756725]
  Rotation:
  [[ 0.0291279132022616  0.943348117774383   0.3305236653615146]
   [-0.6314893722773642  0.2736861619970226 -0.7254771239895024]
   [-0.7748372328258508 -0.1875905472641639  0.6036862175036875]]
  ---------------------------------------->})

In [15]:
help(butane[0].scramble)

Help on method scramble in module qcelemental.models.molecule:

scramble(*, do_shift: bool = True, do_rotate=True, do_resort=True, deflection=1.0, do_mirror=False, do_plot=False, do_test=False, run_to_completion=False, run_resorting=False, verbose=0) method of qcelemental.models.molecule.Molecule instance
    Generate a Molecule with random or directed translation, rotation, and atom shuffling.
    Optionally, check that the aligner returns the opposite transformation.
    
    Parameters
    ----------
    ref_mol : qcel.models.Molecule
        Molecule to perturb.
    do_shift : bool or array-like, optional
        Whether to generate a random atom shift on interval [-3, 3) in each
        dimension (`True`) or leave at current origin. To shift by a specified
        vector, supply a 3-element list.
    do_rotate : bool or array-like, optional
        Whether to generate a random 3D rotation according to algorithm of Arvo.
        To rotate by a specified matrix, supply a 9-element l

In [11]:
butane[0].geometry

array([[ 0.60309252, -2.0666753 , -2.95631542],
       [-0.54975128,  2.07257294,  2.96267825],
       [ 0.17543623, -1.41965569, -0.1899598 ],
       [-0.17535536,  1.41986451,  0.18990506],
       [-0.98243014, -1.42706018, -4.12126516],
       [ 2.32107194, -1.14665691, -3.64966894],
       [ 0.81868895, -4.10783439, -3.21556669],
       [ 1.07104045,  1.43010767,  4.07529687],
       [-2.24715359,  1.16149057,  3.71618302],
       [-0.73832413,  4.11600143,  3.22440978],
       [ 1.79270627, -2.08396319,  0.92115557],
       [-1.4961426 , -2.4339562 ,  0.49460988],
       [-1.81551707,  2.07754179, -0.89074739],
       [ 1.48034939,  2.43606453, -0.52991943]])

In [12]:
butane[0].symbols

['C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H']

In [13]:
butane_geometries = [butane[0].geometry.copy(), butane[1].geometry.copy()]

In [22]:
def calculate_distance(rA, rB):
    """Calculate the distance between points A and B"""
    dist_vec = (rA - rB)
    distance = np.linalg.norm(dist_vec)
    return distance

def build_bond_list(coordinates, max_bond=1.55, min_bond=0):
    """
    This function takes min and max bond distances and 
    """
    num_atoms = len(coordinates)
    
    bonds = {}
    
    for atom1 in range(num_atoms):
        for atom2 in range(atom1, num_atoms):
            distance = calculate_distance(coordinates[atom1], coordinates[atom2])
            
            if distance > min_bond and distance < max_bond:
                bonds[(atom1, atom2)] = distance
    
    return bonds

In [31]:
atom1 = butane_geometries[0][0]
atom2 = butane_geometries[0][1]
measured_distance = calculate_distance(atom1, atom2)
print(measured_distance)

print(butane[0].measure([0,1]))

7.314158248564329
7.31415824856433


In [33]:
atom3 = butane_geometries[1][2]
atom10 = butane_geometries[1][9]

measured_distance2 = calculate_distance(atom3, atom10)
print(measured_distance2)

print(butane[1].measure([2,9]))

6.71634950813261
6.71634950813261


In [23]:
# This didn't work cause qc elemental uses bohr as units for bond length. and we put 1.55 as angstroms. 
bond_list = build_bond_list(butane_geometries[0])
print(bond_list)

{}


In [27]:
butane[0].connectivity

[(0, 2, 1.0),
 (0, 4, 1.0),
 (0, 5, 1.0),
 (0, 6, 1.0),
 (1, 3, 1.0),
 (1, 7, 1.0),
 (1, 8, 1.0),
 (1, 9, 1.0),
 (2, 3, 1.0),
 (2, 10, 1.0),
 (2, 11, 1.0),
 (3, 12, 1.0),
 (3, 13, 1.0)]

In [35]:
import qcelemental

angstrom_to_bohr = qcelemental.constants.conversion_factor("angstrom","bohr")
angstrom_to_bohr

1.8897261254578281

In [36]:
1.55*1.8897261254578281

2.9290754944596338

In [37]:
bond_list = build_bond_list(butane_geometries[0], max_bond=2.93)
bond_list

{(0, 2): 2.873020656801253,
 (0, 4): 2.068839651551603,
 (0, 5): 2.068484041315794,
 (0, 6): 2.068821759435787,
 (1, 3): 2.873059651780396,
 (1, 7): 2.068247482474781,
 (1, 8): 2.0685780442929644,
 (1, 9): 2.0687346633381822,
 (2, 3): 2.8862132661474598,
 (2, 10): 2.0715801221019885,
 (2, 11): 2.0716218178677623,
 (3, 12): 2.0713472807014583,
 (3, 13): 2.071754810836534}

In [38]:
butane[0].connectivity

[(0, 2, 1.0),
 (0, 4, 1.0),
 (0, 5, 1.0),
 (0, 6, 1.0),
 (1, 3, 1.0),
 (1, 7, 1.0),
 (1, 8, 1.0),
 (1, 9, 1.0),
 (2, 3, 1.0),
 (2, 10, 1.0),
 (2, 11, 1.0),
 (3, 12, 1.0),
 (3, 13, 1.0)]

In [ ]:
def build_angle_list(coordinates, max_bond=1.55, min_bond=0):
    """
    This function takes min and max bond distances and 
    """
    num_atoms = len(coordinates)
    
    bonds = {}
    
    for atom1 in range(num_atoms):
        for atom2 in range(atom1, num_atoms):
            distance = calculate_distance(coordinates[atom1], coordinates[atom2])
            
            if distance > min_bond and distance < max_bond:
                bonds[(atom1, atom2)] = distance
    
    return bonds

In [43]:
# use qcportal to access geometry optimization calculation
# use query_procedures
# id = 2658710

geo_opt = client.query_procedures(id=2658710)

In [46]:
geo_opt[0].get_final_molecule()

You appear to be running in JupyterLab (or JavaScript failed to load for some other reason). You need to install the 3dmol extension: 
 jupyter labextension install jupyterlab_3dmol

<Molecule(name='C54H18' formula='C54H18' hash='3fd70b3')>

In [48]:
dir(geo_opt[0])

['Config',
 '__abstractmethods__',
 '__annotations__',
 '__class__',
 '__config__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__fields__',
 '__fields_set__',
 '__format__',
 '__ge__',
 '__get_validators__',
 '__getattr__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__slots__',
 '__str__',
 '__subclasshook__',
 '__validators__',
 '__values__',
 '__weakref__',
 '_abc_impl',
 '_calculate_keys',
 '_custom_root_type',
 '_decompose_class',
 '_get_key_factory',
 '_get_value',
 '_hash_indices',
 '_iter',
 '_json_encoder',
 '_kvstore_getter',
 '_schema_cache',
 'build_schema_input',
 'cache',
 'check_client',
 'check_keywords',
 'check_program',
 'client',
 'construct',
 'copy',
 'created_on',
 'dict',
 'energies',
 'error',
 'extras',
 'fields',
 'fin

In [55]:
initial = geo_opt[0].get_initial_molecule()

final = geo_opt[0].get_final_molecule()

initial.show()
#final.show()

You appear to be running in JupyterLab (or JavaScript failed to load for some other reason). You need to install the 3dmol extension: 
 jupyter labextension install jupyterlab_3dmol

In [54]:
# Since this is from QM calculations it does not have the bond information. 
initial.connectivity

In [63]:
# Now we are using our calculate bond function to get the bond information.
initial_coordinates = initial.geometry.copy()
final_coordinates = final.geometry.copy()

initial_bonds = build_bond_list(initial.geometry.copy(), max_bond=2.93)
final_bonds = build_bond_list(final_coordinates, max_bond=2.93)
#initial_bonds

In [68]:
final_bonds()

TypeError: 'dict' object is not callable

In [78]:
# compare the two dictionaries inital bonds and final bonds to find the change in bond length for each bond.

def calculate_diff(r1, r2):
    diff = r2 -r1
    return diff

for i in initial_bonds:
    diff = calculate_diff(initial_bonds[i], final_bonds[i])
    print(f" Differences for bond {i} from its initial length to the final length is {diff}.")

 Differences for bond (0, 1) from its initial length to the final length is -0.12125783998247419.
 Differences for bond (0, 5) from its initial length to the final length is 0.03652933845980799.
 Differences for bond (0, 54) from its initial length to the final length is 0.0013072821258468537.
 Differences for bond (1, 6) from its initial length to the final length is 0.0365286356592871.
 Differences for bond (1, 55) from its initial length to the final length is 0.0013065023782292684.
 Differences for bond (2, 3) from its initial length to the final length is -0.12125319998628425.
 Differences for bond (2, 9) from its initial length to the final length is 0.036530668675503364.
 Differences for bond (2, 56) from its initial length to the final length is 0.0013062416111879749.
 Differences for bond (3, 10) from its initial length to the final length is 0.0365312833547744.
 Differences for bond (3, 57) from its initial length to the final length is 0.0013068556466429015.
 Differences for

In [75]:
for i in initial_bonds:
    print(initial_bonds[i])

2.6853008199999997
2.685300947458371
2.0494834766860643
2.6853009524690883
2.0494834766860643
2.6853008199999997
2.685300947458371
2.0494834766860643
2.6853009524690883
2.0494834766860643
2.685300829999999
2.685300829993184
2.0494834770587396
2.6852998829666923
2.68530082
2.6852998879774117
2.6852998879774117
2.0494834871062877
2.685300829999999
2.685300829993184
2.0494834770587396
2.6852998829666923
2.68530082
2.6852998879774117
2.6852998879774117
2.0494834871062877
2.685300829999999
2.6852998829666923
2.049483475383679
2.685300829993184
2.6853008199999997
2.6852998829666923
2.6852998879774117
2.68530082
2.6852998879774117
2.6852998879774117
2.049483480394398
2.685300829999999
2.6852998829666923
2.049483475383679
2.685300829993184
2.6853008199999997
2.6852998829666923
2.6852998879774117
2.68530082
2.6852998879774117
2.6852998879774117
2.049483480394398
2.685300947458371
2.0494834799999992
2.685300829999999
2.6853018944844873
2.685300947458371
2.68530082
2.6853009524690883
2.6853009524